style: Remove trailing whitespaces

diff --git a/.tekton/rhtap-perf-integration-test.yaml b/.tekton/rhtap-perf-integration-test.yaml
--- a/.tekton/rhtap-perf-integration-test.yaml
+++ b/.tekton/rhtap-perf-integration-test.yaml
@@ -4,7 +4,7 @@ metadata:
   name: integration-test-app
 spec:
   description: >-
-    Expects a Snapshot of a simple application with endpoint containing the expected output to be deployed on an environment. 
+    Expects a Snapshot of a simple application with endpoint containing the expected output to be deployed on an environment.
     A secret containing the kubeconfig for the environment needs to be mounted via the cluster-credentials workspace binding.
     The route to the single component is expected to have the same name as the component (default appstudio behavior).
   params:
@@ -23,11 +23,11 @@ spec:
     - description: 'Horreum Test Name'
       name: HR_TEST_NAME
       default: ""
-      type: string      
+      type: string
     - description: 'Horreum regression variable'
       name: HR_REG_VAR
       default: ""
-      type: string        
+      type: string
   tasks:
     - name: provision-env
       taskSpec:
@@ -51,7 +51,7 @@ spec:
               #!/bin/bash
               set -ex
               set -o pipefail
-      
+
               cat <<EOF > space_request.yaml
               apiVersion: toolchain.dev.openshift.com/v1alpha1
               kind: SpaceRequest
@@ -66,9 +66,9 @@ spec:
               spec:
                 tierName: appstudio-env
               EOF
-      
+
               SPACEREQUEST_NAME=$(oc create -f space_request.yaml -o=jsonpath='{.metadata.name}')
-      
+
               if oc wait spacerequests $SPACEREQUEST_NAME --for=condition=Ready --timeout=5m -n $KONFLUXNAMESPACE; then
                 secretRef=$(oc get spacerequests $SPACEREQUEST_NAME -o=jsonpath='{.status.namespaceAccess[0].secretRef}')
                 echo -n $secretRef | tee $(results.secretRef.path)
@@ -85,7 +85,7 @@ spec:
         - name: PORT
           value: $(params.PORT)
         - name: HR_TEST_NAME
-          value: $(params.HR_TEST_NAME)          
+          value: $(params.HR_TEST_NAME)
         - name: HR_REG_VAR
           value: $(params.HR_REG_VAR)
       taskSpec:
@@ -99,18 +99,18 @@ spec:
             name: PORT
             description: Application endpoint Port
           - name: HR_TEST_NAME
-            description: 'Horreum Test Name'            
+            description: 'Horreum Test Name'
           - name: HR_REG_VAR
-            description: 'Horreum regression variable'            
+            description: 'Horreum regression variable'
         results:
           - name: APP_URL
             description: APP URL
           - name: test_name
             description: Test name
           - name: reg_var
-            description: Regression variable             
+            description: Regression variable
           - name: TEST_OUTPUT
-            description: Test output             
+            description: Test output
         steps:
         - image: registry.redhat.io/openshift4/ose-cli:latest
           env:
@@ -134,7 +134,7 @@ spec:
               valueFrom:
                 secretKeyRef:
                   name: ocm
-                  key: client_secret                      
+                  key: client_secret
           script: |
             #!/usr/bin/env bash
             cat <<< "$KUBECONFIG_VALUE" > /tmp/cfg
@@ -168,27 +168,27 @@ spec:
             ROUTE_NAME=$(oc get --kubeconfig /tmp/cfg routes trex -o name --insecure-skip-tls-verify)
             HOST=$(oc get --kubeconfig /tmp/cfg "${ROUTE_NAME}" -o jsonpath={.spec.host}  --insecure-skip-tls-verify)
             echo "Found target host ${HOST} for app ${APPLICATION_NAME}"
-            
+
             # Check the application endpoint
             ENDPOINT_OUTPUT=$(curl -k http://${HOST}:${PORT})
             echo -e "The endpoint outputs the following:\n ${ENDPOINT_OUTPUT}"
             echo -e "Snapshot output:\n ${SNAPSHOT}"
 
-            echo ${HOST} > /tekton/home/endpoint_url            
+            echo ${HOST} > /tekton/home/endpoint_url
             echo -n ${HOST} | tee $(results.APP_URL.path)
             if [ -z $(params.HR_TEST_NAME) ]
             then
               echo '$(params.SNAPSHOT)'|jq -r .components[].name |  tr -d '\n\t' | tee $(results.test_name.path)
             else
               echo -n  '$(params.HR_TEST_NAME)' | tee $(results.test_name.path)
-            fi            
-            
+            fi
+
             if [ -z $(params.HR_REG_VAR) ]
             then
               echo -n 'iteration_duration' | tee $(results.reg_var.path)
             else
               echo -n '$(params.HR_REG_VAR)' | tee $(results.reg_var.path)
-            fi             
+            fi
     - name: perf-benchmark
       params:
         - name: url
@@ -201,7 +201,7 @@ spec:
         params:
           - name: url
           - name: test_name
-          - name: reg_var          
+          - name: reg_var
         steps:
         - image: grafana/k6
           name: run-perf
@@ -210,7 +210,7 @@ spec:
               valueFrom:
                 secretKeyRef:
                   name: ocm
-                  key: ocmtoken          
+                  key: ocmtoken
           script: |
             #!/usr/bin/env sh
             export
@@ -241,7 +241,7 @@ spec:
               valueFrom:
                 secretKeyRef:
                   name: horreum
-                  key: horreum_user          
+                  key: horreum_user
           script: |
             set -xv
             echo "Transform result to json format"
@@ -254,11 +254,11 @@ spec:
             testid=$(curl -s -k -X GET  ${HORREUM_URI}'/api/test/byName/'$test_name|jq -r .id)
             varid=$(curl -s -k -X GET  ${HORREUM_URI}'/api/alerting/variables?test='$testid|jq -r --arg regvar "$reg_var" '.[] | select(.name==$regvar)| .id ')
             changes=`curl -s -k -X GET ${HORREUM_URI}'/api/alerting/changes?var='$varid  |jq  '.| length'`
-            if [ -z  $changes ] || [ $changes -gt 0  ] ;then echo "Regression check failed";exit 1;fi            
+            if [ -z  $changes ] || [ $changes -gt 0  ] ;then echo "Regression check failed";exit 1;fi
       runAfter:
         - deploy-app
   finally:
-    - name: cleanup  
+    - name: cleanup
       params:
         - name: aggregateTasksStatus
           value: "$(tasks.status)"
@@ -268,7 +268,7 @@ spec:
         params:
           - name: aggregateTasksStatus
         steps:
-        - image: quay.io/yogananth_subramanian/curl-yq-jq  
+        - image: quay.io/yogananth_subramanian/curl-yq-jq
           name: step1
           script: |
             RESULT="SUCCESS"
